name: disir_package
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.2
  - scipy=1.8.0
  - pip=22.0.4
  - pandas=1.4.1
  - matplotlib=3.5.1
  - r-seurat=3.2.3
  - r-spatstat=1.64-1
  - gdown=4.4.0
  - r-hdf5r=1.3.5
  - datatable=0.11.1
  - pip:
    - ortools==9.2.9972
